name: sip_ai_app
description: AI SIP Investment App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.0
  fl_chart: ^0.68.0
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true